export const hindiHateResponse = [
  'aur bhailog kya haal chaal',
  'sab Theek',
  'sab theek hai',
  'sab theek hai bhai',
  'are bhai',
  'aree bhai',
  'bhai',
  'bhaiyo',
  'bhaiyon',
  'nhi',
  'acha',
  'kya',
  'kaise',
  'kaise ho',
  'kaise ho bhai',
  'kaise ho bhaiyo',
  'chalo',
  'chalo bhai',
  'chalo bhaiyo',
  'yaar',
  'milega',
  'kehde',
  'mujhe',
  'mere',
  'khud ni',
  'thik',
  'jab',
  'pata',
];

export const badwords = [
  'mf',
  'mother fucker',
  'motherchod',
  'bhenchod',
  'fuck',
  'fk',
];

export const greetings = [
  'hello',
  'hi',
  'hii',
  'hey',
  'hy',
  'hui',
  'huii',
  'yo',
  'yoo',
  'sup',
  "what's up",
];

export const dayGreetings = [
  'good morning',
  'good afternoon',
  'good evening',
  'good night',
];

export const howAreYouResponses = [
  'how are you',
  'how r u',
  'how are u',
  'how are you doing',
  'how are you feeling',
  'how are you today',
  'how are you feeling today',
];

export const boss = [
  'who is your boss',
  'who is your boss?',
  'who is ur boss',
  'who is ur boss?',
  `who's your boss`,
  `who's your boss?`,
  `who's ur boss`,
  `who's ur boss?`,
  `who is your owner`,
  `who is your owner?`,
  `who is ur owner`,
  `who is ur owner?`,
  `who's your owner`,
  `who's your owner?`,
  `who created you`,
  'who created you?',
];

export const bye = ['bye', 'goodbye', 'good bye', 'see you', 'see you later'];

export const goods = [
  'ok',
  'okay',
  'kk',
  'alright',
  'thank you',
  'thanks',
  'thx',
  'tx',
  'ty',
  'tysm',
  'thank you so much',
  'good',
  'well',
  'great',
  'awesome',
  'amazing',
  'fantastic',
  'nice',
  'cool',
  'sweet',
  'superb',
  'excellent',
  'wonderful',
];

export const bads = [
  'not good',
  'not well',
  'bad',
  'not good',
  'not well',
  'not great',
  'not awesome',
  'not amazing',
  'not fantastic',
  'not nice',
  'not cool',
  'not sweet',
  'not superb',
  'not excellent',
  'not wonderful',
  'nood',
  'noob',
  'noobie',
  'noobies',
  'noobz',
  'noobs',
];
