export const hindiHateResponse = [
  'aur bhailog kya haal chaal',
  'sab Theek',
  'sab theek hai',
  'sab theek hai bhai',
  'are bhai',
  'aree bhai',
  'bhai',
  'bhaiyo',
  'bhaiyon',
  'nhi',
  'acha',
  'kya',
  'kaise',
  'kaise ho',
  'kaise ho bhai',
  'kaise ho bhaiyo',
  'chalo',
  'chalo bhai',
  'chalo bhaiyo',
  'yaar',
  'milega',
  'kehde',
  'mujhe',
  'mere',
  'khud ni',
  'thik',
  'jab',
  'pata',
  'haan',
  'nahi',
  'nahin',
  'nahi hai',
  'nahin hai',
  'nahi hain',
  'nahin hain',
  'kyun',
  'kyun nahi',
  'kaise karun',
  'kaise karoge',
  'kaise karein',
  'kaise karega',
  'kaise karegi',
  'kaise karenge',
  'kaise karengi',
  'main hoon',
  'main hu',
  'main hua',
  'main hue',
  'main hui',
  'main huye',
  'tum ho',
  'tum hua',
  'tum hue',
  'tum hui',
  'tum huye',
  'tu hai',
  'tu hua',
  'tu hue',
  'tu hui',
  'tu huye',
  'hum hain',
  'hum hue',
  'hum hui',
  'hum huye',
  'aap hain',
  'aap hue',
  'aap hui',
  'aap huye',
  'vah',
  'vah hai',
  'vah hua',
  'vah hue',
  'vah hui',
  'vah huye',
  've hain',
  've hue',
  've hui',
  've huye',
  'yeh hai',
  'yeh hua',
  'yeh hue',
  'yeh hui',
  'yeh huye',
  'woh hai',
  'woh hua',
  'woh hue',
  'woh hui',
  'woh huye',
  'kaun',
  'kaun hai',
  'kaun hua',
  'kaun hue',
  'kaun hui',
  'kaun huye',
  'kya hai',
  'kya hua',
  'kya hue',
  'kya hui',
  'kya huye',
  'kaise hai',
  'kaise hua',
  'kaise hue',
  'kaise hui',
  'kaise huye',
  'kab',
  'kab hai',
  'kab hua',
  'kab hue',
  'kab hui',
  'kab huye',
  'kahan',
  'kahan hai',
  'kahan hua',
  'kahan hue',
  'kahan hui',
  'kahan huye',
  'kisne',
  'kisne hai',
  'kisne hua',
  'kisne hue',
  'kisne hui',
  'kisne huye',
  'kya kar raha hai',
  'kya kar rahi hai',
  'kya kar rahe hain',
  'kya kar rahi hain',
  'kya kar raha tha',
  'kya kar rahe the',
  'kya kar rahi thi',
  'kya kar raha hoga',
  'kya kar rahi hogi',
  'kya kar rahe honge',
  'kya kar rahi hogi',
];

export const badwords = [
  'mf',
  'mother fucker',
  'motherchod',
  'bhenchod',
  'fuck',
  'fk',
];

export const greetings = [
  'hello',
  'hi',
  'hii',
  'hey',
  'hy',
  'hui',
  'huii',
  'yo',
  'yoo',
  'sup',
  "what's up",
];

export const dayGreetings = [
  'good morning',
  'good afternoon',
  'good evening',
  'good night',
];

export const howAreYouResponses = [
  'how are you',
  'how r u',
  'how are u',
  'how are you doing',
  'how are you feeling',
  'how are you today',
  'how are you feeling today',
];

export const boss = [
  'who is your boss',
  'who is your boss?',
  'who is ur boss',
  'who is ur boss?',
  `who's your boss`,
  `who's your boss?`,
  `who's ur boss`,
  `who's ur boss?`,
  `who is your owner`,
  `who is your owner?`,
  `who is ur owner`,
  `who is ur owner?`,
  `who's your owner`,
  `who's your owner?`,
  `who created you`,
  'who created you?',
];

export const bye = ['bye', 'goodbye', 'good bye', 'see you', 'see you later'];

export const goods = [
  'ok',
  'okay',
  'kk',
  'alright',
  'thank you',
  'thanks',
  'thx',
  'tx',
  'ty',
  'tysm',
  'thank you so much',
  'good',
  'well',
  'great',
  'awesome',
  'amazing',
  'fantastic',
  'nice',
  'cool',
  'sweet',
  'superb',
  'excellent',
  'wonderful',
  'insane',
  'gg',
  'good game',
  'awesome',
  'fine',
  'good job',
];

export const goodsReaction = [
  '👍',
  '😁',
  '😍',
  '🥰',
  '🤩',
  '☺',
  '😉',
  '❤',
  '💖',
];

export const bads = [
  'not good',
  'not well',
  'bad',
  'not good',
  'not well',
  'not great',
  'not awesome',
  'not amazing',
  'not fantastic',
  'not nice',
  'not cool',
  'not sweet',
  'not superb',
  'not excellent',
  'not wonderful',
  'nood',
  'noob',
  'noobie',
  'noobies',
  'noobz',
  'noobs',
];

export const badsReaction = ['👎', '😥', '😭', '🥺', '☹️', '😥'];
